### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by darekodz** [Stanko/html-canvas-video-player#1]
Hi,
This is very good piece of code. 
Are you going to add support for sound?

**Comment by Stanko** [comment]
Thank you! I've made it as a part of a bigger project, and decided to extract it and open source. That project has no need for audio.

Only way to audio I could think of is keeping the separate audio file, and play it in background. It is easy to implement, but I think that is not really practical solution. I'm open to suggestions.

**Comment by darekodz** [comment]
Thanks for your quick feeedback!

I saw one page:
http://inread-experience.teads.tv/ (open on iphone and scroll down). I don't know how they did it but they have canvas player and audio too. Maybe they are using separated audio file...

**Comment by adityad99** [comment]
Hi,
I tried opening the demo page form iPhone 5s (iOS version 9.2) , somehow the video is not playing.Can you please look into this?
Thanks in advance.

**Comment by Stanko** [comment]
I just tested on two iphones 5s and 6s, and two ipads, it works fine. You need to tap the video. Use .play() method from javascript if you want to autoplay it.

And this is totally unreleated with the issue, please don't do that. Thanks

**Comment by Stanko** [comment]
@darekodz I just pushed audio support. Feel free to play with it :)

**Comment by darekodz** [comment]
Cool - thanks for the info!

POZDRAWIAM
d

2016-01-08 15:34 GMT+01:00 Stanko notifications@github.com:
