### ISSUE TITLE
Changing video

### ISSUE THREAD

**Issue by percramer** [Stanko/html-canvas-video-player#10]
Hi,

great project! I tried switching the video source, but i am facing a problem with the audio. At first the new video was played by the native player again, but i fixed that by changing the video source through java and then recreate the canvasPlayer object. But it still plays the audio of the previous video.

i  added a function to clear the audio using :

if (this.options.audio) {
        this.audio.parentNode.removeChild(this.audio);

but that also doesn't seem to do the trick.

Regards,

Per

**Comment by Stanko** [comment]
Currently there is no support for switching video. 

Safest thing to do is to call `unbind` method to remove all of the listeners. Then replace the HTML and create new instance of the canvas player. Hope that helps!

https://github.com/Stanko/html-canvas-video-player/blob/gh-pages/js/canvas-video-player.js#L176

**Comment by percramer** [comment]
ok thanks, i will try it. If it works ok then i will create a method for it an do a pull request!

**Comment by LanceMango** [comment]
Hi stanko,

for me, audio is not working on iPhone6. and the whole plug isn't working on android. should it?

Greetings
Lance
