### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by robbp2** [Stanko/html-canvas-video-player#11]
Is it possible to have multiple inline videos within a page? I currently have 4 videos in my page I'd like to play inline. Here is my code:

```
$(document).ready(function(){
  $('canvas').each(function() {
    var canvasVideo = new CanvasVideoPlayer({
      videoSelector: '.js-video',
      canvasSelector: '.js-canvas',
      hideVideo: false, // should script hide the video element
      autoplay: true,
      audio: false,
      resetOnLastFrame: true
    });
  });
});
```

However, this still only works on the very first video on the page. How can I get it to work with multiple videos?

**Comment by Stanko** [comment]
You are using same selectors every time

```
videoSelector: '.js-video',
canvasSelector: '.js-canvas',
```

Use something like this

```
videoSelector: '.js-video-' + videoIndex,
canvasSelector: '.js-canvas-' + videoIndex,
```

Of course, you need to add same classes to your video and canvas elements.

**Comment by robbp2** [comment]
Yes, worked perfectly, thank you. Awesome plugin btw :)

**Comment by Stanko** [comment]
Thanks mate, glad it worked :) feel free to share a link where you use it, I would like to create a small showcase.

**Comment by robbp2** [comment]
Sure thing, as soon as the project's complete.

**Comment by Stanko** [comment]
Sweet, thanks! Closing this one.
