### ISSUE TITLE
Protection from double calling on selector.

### ISSUE THREAD

**Issue by wcatron** [Stanko/html-canvas-video-player#12]
I ran into an unknown issue that I spent an hour trying to track down, turns out it was all my fault and I had called CanvasVideoPlayer twice on the same selector. It caused the audio to stop working and the video to play quickly. Perhaps this could be built into the library to prevent double calling it?

**Comment by Stanko** [comment]
I'm in a middle of a work trip, and I won't be able to do in the following few weeks. If you can, it would be nice to issue a pull request for that feature.

**Comment by wcatron** [comment]
I'll look into it!
