### ISSUE TITLE
Looping video

### ISSUE THREAD

**Issue by graybeltran** [Stanko/html-canvas-video-player#13]
Having a hard time getting the video to loop after it initially plays. Am I missing something or is that not an option?

**Comment by Stanko** [comment]
There was no option to loop a video. I just added it and pushed to the repo. Please try adding `loop: true` to the options passed.
Cheers!

**Comment by tranthailinh** [comment]
Hi Stanko, 
i just applied your solution to my prj, but i want to play a video on Android os, can u help me to suggest a way to do it, Thanks and best regard!

**Comment by Stanko** [comment]
Just use native HTML video.

**Comment by tranthailinh** [comment]
Thanks so much Stanko!
