### ISSUE TITLE
InvalidStateError within loop() on iOS < 8

### ISSUE THREAD

**Issue by joshharbaugh** [Stanko/html-canvas-video-player#16]
I've been troubleshooting some issues with iOS devices using versions of 7 and below. Upon calling the 'play' method I get an InvalidStateError referenced here: https://github.com/Stanko/html-canvas-video-player/blob/gh-pages/js/canvas-video-player.js#L238

`InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.`

Wasn't sure if it was a limitation of video in older iOS versions, but thought I'd bring it up.

**Comment by Stanko** [comment]
I don't have access to the device with iOS7, if you can isolate the problem, that would be nice.

**Comment by joshharbaugh** [comment]
Sure, https://github.com/Stanko/html-canvas-video-player/blob/gh-pages/js/canvas-video-player.js#L144 never fires on an iOS device < 8

Edit: I should say it doesn't fire until the this.video element is playing. If you manually call this.video.play() it'll fire, but not before.

**Comment by Stanko** [comment]
I think I'll close this one, as nobody in industry still supports iOS7.
