### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by darekodz** [Stanko/html-canvas-video-player#2]
Hi,
The audio feature is really cool - I didn't think It will be so easy.
I know that this solution is dedicated for iphones but maybe you will know why it doesn't work on Android devices? (my example: motorola moto g 2gen). Are there any limitations regarding canvas on android?

**Comment by Stanko** [comment]
Not that I know of, but I will take a look.

**Comment by Stanko** [comment]
It seems this is a bug (or a feature :smile:) in Chrome. It can't pull image from the HTML5 video for some reason. I think it is easiest to use native video in this case, and keep the canvas only for iPhones. You can still have full control over it in JavaScript.

I have no intention to fix it, as native video works by itself. If someone wants to explore it further, feel free to open a pull request.

**Comment by darekodz** [comment]
Hi,
Thanks for your quick feedback. 
I've analyzed this topic too and I agree that the only possible solution is using video tag in case of android. The only issue of such solution is that there will be not autoplay:(

BTW: also interesting solution is here: http://phoboslab.org/log/2013/05/mpeg1-video-decoder-in-javascript
