### ISSUE TITLE
Register your library to Bower

### ISSUE THREAD

**Issue by aduh95** [Stanko/html-canvas-video-player#20]
Greetings,

I use Bower to help me manage my dependencies on my web projects, which is the best way I found to keep my dependencies up to date.
If you don't know Bower yet, you can find on its website a good explanation on how to [register your library ](https://bower.io/docs/creating-packages/#register).

Thanks a lot for your great work!

**Comment by Stanko** [comment]
Sorry, but I have no plans doing this, feel free to fork it and publish on bower.
