### ISSUE TITLE
is this code compaitble with only IOS10 and above?

### ISSUE THREAD

**Issue by priyankasoni05** [Stanko/html-canvas-video-player#22]
hi
i had following the same code but i found this code is compatible with only IOS10 and above browsers.
below that its not working?

**Comment by Stanko** [comment]
I just tested, and it works on iOS9, as that is the whole point.

However iOS10 supports it natively, so you don't really need it, only as a fallback.
https://webkit.org/blog/6784/new-video-policies-for-ios/
