### ISSUE TITLE
Multiple instance example?

### ISSUE THREAD

**Issue by evilcranberry** [Stanko/html-canvas-video-player#25]
Anyway you could add a multiple instance example of using the canvas video player plugin? I'm new to jquery and I'm having a lot of trouble implementing multiple video backgrounds on my webpage. Any practical examples of this implementation in the documentation would be really appreciated.

**Comment by Stanko** [comment]
It is pretty straight forward. You just need to create two instances, and pass them different options.

```javascript
var video1 = new CanvasVideoPlayer({
    videoSelector: '.js-video-one',
    canvasSelector: '.js-canvas-one'
});

var video2 = new CanvasVideoPlayer({
    videoSelector: '.js-video-two',
    canvasSelector: '.js-canvas-two'
});

```

and your html should look something like this

```html
<!-- first video -->
<div>
  <video class="video js-video-one" muted>
    <source src="video1.mp4" type="video/mp4">
  </video>

  <canvas class="canvas js-canvas-one"></canvas>
</div>

<!-- second video -->
<div>
  <video class="video js-video-two" muted>
    <source src="video2.mp4" type="video/mp4">
  </video>

  <canvas class="canvas js-canvas-two"></canvas>
</div>
```


P.S. This library is not using jQuery :)

**Comment by evilcranberry** [comment]
Well I feel dumb now :) Thank you so much for this! I thought I had to add some kind of index thing to the main class. And thank you for this plugin, it's a real life saver because I need it to work on both iOS and PC platform.

**Comment by Stanko** [comment]
No problem, glad it helped. Don't loose enthusiasm with the problems like this one.

And thanks!
