### ISSUE TITLE
Add note to README about autoplaying video on iOS 10

### ISSUE THREAD

**Issue by chrisladd** [Stanko/html-canvas-video-player#28]
Thanks so much for this—I found it incredibly useful for a site I used for [one of my apps](http://www.betternotesapp.com/).

In [launching another one](http://www.tabbankapp.com/), I was trying to update performance, and was pleased to find that WebKit will autoplay videos without sound with no problems on iOS10 and above:
https://webkit.org/blog/6784/new-video-policies-for-ios/

So this would autoplay inline by default on an iPhone:

```
<video src="....mp4" autoplay muted playsinline poster="...jpg"></video>
```

Would it be worth updating your README to make clear that, while this software was a godsend for previous versions of iOS, it's no longer necessary for modern versions?

Thanks!
Chris

**Comment by Stanko** [comment]
Hey @chrisladd,
You are totally right, I mentioned that couple of times in the issues, but not in the readme and demo. I will update it soon, thanks!

**Comment by Stanko** [comment]
Updated both readme and demo, thanks again!
