### ISSUE TITLE
hi.how can you use drawImage on safari? 

### ISSUE THREAD

**Issue by HUGY1** [Stanko/html-canvas-video-player#30]
hi there. i am trying to play video stream by canvas(context.drawImage), which works in chorme .   
i noticed that you didnt do anything but drawImage still works on Safari.

and i found this .

> Note: Video as a source for the canvas drawImage() method is not currently supported on iOS. 

how can i fix it.  thanks

**Comment by Stanko** [comment]
Hello,
Use native video, instead of canvas player, you can see the announcement here:
https://webkit.org/blog/6784/new-video-policies-for-ios/

This is already noted in the deprecation notice
https://github.com/Stanko/html-canvas-video-player#depreciation-notice

Cheers!
